# This is a basic workflow to help you get started with Actions

name: CFDtest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs: 
          tunnel_token:
            description: ' Your Token : '
            required: true
            

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: pre configurations.
        run: |
            sudo apt-get update -y ; sudo apt-get install apache2 -y
            sudo service apache2 start 
            sudo service apache2 status 
            cat /etc/apache2/ports.conf
            sleep 3
      # Runs a set of commands using the runners shell
      - name: test the tunnel.
        run: ${{ github.event.inputs.tunnel_token }}
        
        
