# This is a basic workflow to help you get started with Actions

name: simpleShh

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ngrok_token:
        description: 'Enter the ngrok auth token here'
        required: true
      username:
        description: ' Enter a user name ; Example: f1ver'
        required: true
      password:
        description: ' Enter a password at least 4 digits'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: primary configs
        run: |
           apt-get update -y &>/dev/null &
           apt-get install ssh -y &>/dev/null &
           apt-get install sudo &>/dev/null &
           echo -----[ completed ]------
      - name: user settings
        run: |
           if [[ -z "${{ github.event.inputs.username }}" ]]; then
             echo "Please set 'LINUX_USER_PASSWORD' for user: $USER"
             exit 3
           fi
           
           sudo -i
           sudo useradd -m ${{ github.event.inputs.username }}
           sudo adduser ${{ github.event.inputs.username }} sudo
           echo "${{ github.event.inputs.username }}:${{ github.event.inputs.password }}" | sudo chpasswd
           sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
           sudo echo -e "${{ github.event.inputs.password }}\n${{ github.event.inputs.password }}" | sudo passwd "$USER"       
      - name: setting up ssh
        run: |
           sudo service ssh status
           echo ------compltd-------
      - name: setting up Ngrok
        run: | 
           echo ----[ starting ]----
           wget https://github.com/fennonina/yamlTest-docker/raw/main/assest/ngrok> /dev/null 2>&1
           sudo chmod +x ngrok
           ./ngrok config add-authtoken ${{ inputs.ngrok_token }}
           ./ngrok tcp 22 &>/dev/null &        
      - name: Your Machine details
        run: |
           echo =========================
           echo =========================
           echo
           echo username : ${{ github.event.inputs.username }}
           echo password : ${{ github.event.inputs.password }}
           echo
           echo "SSH Address:"
           wget https://raw.githubusercontent.com/fennonina/yamlTest-docker/main/ngurl.sh > /dev/null 2>&1
           sudo chmod +x ngurl.sh ; sudo ./ngurl.sh
           echo
           echo =========================
           echo =========================
      - name: keep running
        run: |
           sleep 6h
