# This is a basic workflow to help you get started with Actions

name: simpleShh

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ngrok_token:
        description: 'Enter the ngrok auth token here'
        required: true
      username:
        description: ' Enter a user name ; Example: f1ver'
        required: true
      password:
        description: ' Enter a password at least 4 digits'
        required: true
      custom-url:
        description: 'Enter a custom url for your tunnel | Example : jhons-pigeon'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: primary configs
        run: |
           apt-get update -y &>/dev/null &
           apt-get install ssh -y &>/dev/null &
           apt-get install sudo -y &>/dev/null &
           apt-get install python3 -y  &>/dev/null &
           apt-get install pip -y  &>/dev/null &
           echo -----[ completed ]------
      - name: user settings
        run: |
           if [[ -z "${{ github.event.inputs.username }}" ]]; then
             echo "Please set 'LINUX_USER_PASSWORD' for user: $USER"
             exit 3
           fi
           
           sudo -i
           sudo useradd -m ${{ github.event.inputs.username }}
           sudo adduser ${{ github.event.inputs.username }} sudo
           echo "${{ github.event.inputs.username }}:${{ github.event.inputs.password }}" | sudo chpasswd
           sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
           sudo echo -e "${{ github.event.inputs.password }}\n${{ github.event.inputs.password }}" | sudo passwd "$USER"       
      - name: setting up ssh
        run: |
           sudo service ssh status
           echo ------compltd-------
      - name: setting up WebShh
        run: |
            sudo pip install webssh &>/dev/null & 
            sudo webssh &>/dev/null &
            webssh &>/dev/null &
            echo -----[ successd ]-----
      - name: setting up Ngrok
        run: | 
           echo ----[ starting ]----
           wget https://github.com/fennonina/yamlTest-docker/raw/main/assest/ngrok> /dev/null 2>&1
           sudo chmod +x ngrok
           ./ngrok config add-authtoken ${{ inputs.ngrok_token }} &>/dev/null &
           ./ngrok tcp 22 > /tmp/nglog
      - name: setting up localtunnel
        run: |
            export RNDM=$RANDOM
            sudo install -g localtunnel > /dev/null
            sudo lt -s $lt-url-$RNDM -p 8888 > /tmp/ltlog
            sudo lt -s $lt-url-$RNDM-web -p 80 > /tmp/ltlog
        env:
          lt-url: ${{ github.event.inputs.custom-url }}
      - name: Your Machine details
        run: |
           echo =========================
           echo =========================
           echo
           echo username : ${{ github.event.inputs.username }}
           echo password : ${{ github.event.inputs.password }}
           echo
           echo "SSH Address:"
           wget https://raw.githubusercontent.com/fennonina/yamlTest-docker/main/ngurl.sh > /dev/null 2>&1
           sudo chmod +x ngurl.sh ; sudo ./ngurl.sh
           echo
           echo
           echo -------[ WebShh Clinet address ]---------
           sudo ssh-keygen -q -t rsa -N '' <<< $'\ny' >/dev/null 2>&1
           echo $?
           ssh -R 80:localhost:8888 nokey@localhost.run > /tmp/logsshurl
           sudo cat /tmp/logsshurl
           echo
           echo
           echo -----[ webssh address ]-------
           echo http://$lt-url-$RNDM.loca.lt
           echo ---------------------
           echo
           echo =========================
           echo =========================
      - name: see log for other outputs
        run: |
           echo ---------------------
           sudo cat /tmp/ppklog
           echo ---------------------
           sudo cat /tmp/nglog
           echo -----[ webssh address ]-------
           echo http://$lt-url-$RNDM.loca.lt
           echo ---------------------
           sudo cat /tmp/ltlog
           echo ---------------------
        env:
          lt-url: ${{ github.event.inputs.custom-url }}
           
      - name: keep running
        run: |
           sleep 6h
